from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from datetime import datetime

def generate_report(title, score, status, recommendations):
    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = HexColor("#4F46E5")

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    story.append(Paragraph("🛡️ SafeNet AI", title_style))
    story.append(Paragraph("AI Powered Cybersecurity Report", normal))
    story.append(Spacer(1,20))

    story.append(Paragraph(f"<b>Analysis Type:</b> {title}", heading))
    story.append(Paragraph(f"<b>Score:</b> {score}/100", normal))
    story.append(Paragraph(f"<b>Status:</b> {status}", normal))

    story.append(Spacer(1,20))

    story.append(Paragraph("<b>Recommendations</b>", heading))

    if recommendations:
        for item in recommendations:
            story.append(Paragraph(f"• {item}", normal))
    else:
        story.append(Paragraph("No recommendations. Excellent security!", normal))

    story.append(Spacer(1,30))

    story.append(
        Paragraph(
            "<b>Generated by SafeNet AI</b>",
            normal
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer

def generate_chat_report(question, answer):
    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = HexColor("#4F46E5")

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    story.append(Paragraph("🛡️ SafeNet AI", title_style))
    story.append(Paragraph("AI Cybersecurity Assistant Report", normal))
    story.append(Spacer(1, 20))

    story.append(Paragraph("<b>User Question</b>", heading))
    story.append(Paragraph(question, normal))

    story.append(Spacer(1, 15))

    story.append(Paragraph("<b>AI Response</b>", heading))
    story.append(Paragraph(answer.replace("\n", "<br/>"), normal))

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
            normal
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            "<b>Generated by SafeNet AI</b><br/>"
            "AI Powered Cybersecurity Platform",
            normal
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer